name: Travelmaker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Build Angular App
        run: npm run build:app:prod

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Publish GitHub Page
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/apps/travelmaker-app
          enable_jekyll: true

      - name: Publish API on Heroku
        if: success()
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "travelmaker-nestjs-api"
          heroku_email: "marcin.dobroszek@gmail.com"
        env:
          HD_PORT: 80
          HD_TYPEORM_URL: ${{ secrets.TYPEORM_URL }}
          HD_TYPEORM_PORT: ${{ secrets.TYPEORM_PORT }}
          HD_TYPEORM_DATABASE: ${{ secrets.TYPEORM_DATABASE }}
